image: node

before_script:
  - apt update
  - apt upgrade -yqq
  - apt install rsync -yqq 
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm --version
    - date
    - npm run generate
    - date 
    - rsync -av dist/ public/
    - ls -a public/
  artifacts:
    paths:
      - public
  only:
    - master

