image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm --version
    - npm run generate
    - apt update
    - apt upgrade -yqq
    - apt install rsync -yqq  
    - rsync -av dist/ public/
    - ls -a public/
  artifacts:
    paths:
      - public
  only:
    - master

